# Curated scholarship database — major US scholarships for college students
SCHOLARSHIPS = [
    {
        "title": "Gates Scholarship",
        "organization": "Bill & Melinda Gates Foundation",
        "amount": "Full cost of attendance",
        "deadline": "September 15",
        "url": "https://www.thegatesscholarship.org",
        "description": "For outstanding minority students with significant financial need. Covers full cost of college.",
        "requirements": "Pell Grant eligible, minority student, GPA 3.3+, senior in high school or first-year college student",
        "location": "United States",
    },
    {
        "title": "Coca-Cola Scholars Program",
        "organization": "Coca-Cola Scholars Foundation",
        "amount": "$20,000",
        "deadline": "October 31",
        "url": "https://www.coca-colascholarsfoundation.org",
        "description": "Merit-based scholarship for high school seniors demonstrating leadership and service.",
        "requirements": "High school senior, US citizen/permanent resident, GPA 3.0+",
        "location": "United States",
    },
    {
        "title": "Jack Kent Cooke Foundation College Scholarship",
        "organization": "Jack Kent Cooke Foundation",
        "amount": "Up to $55,000/year",
        "deadline": "November",
        "url": "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
        "description": "For high-achieving high school seniors with significant financial need.",
        "requirements": "High school senior, financial need, GPA 3.5+, SAT 1200+ or ACT 26+",
        "location": "United States",
    },
    {
        "title": "Fulbright U.S. Student Program",
        "organization": "U.S. Department of State",
        "amount": "Full funding (tuition, living, travel)",
        "deadline": "October (varies by institution)",
        "url": "https://us.fulbrightonline.org",
        "description": "Grants for graduate study, research, or English teaching abroad.",
        "requirements": "US citizen, bachelor's degree by start of grant, strong academic record",
        "location": "International",
    },
    {
        "title": "Rhodes Scholarship",
        "organization": "Rhodes Trust",
        "amount": "Full Oxford tuition + stipend",
        "deadline": "October",
        "url": "https://www.rhodeshouse.ox.ac.uk",
        "description": "Postgraduate study at Oxford University. One of the most prestigious scholarships.",
        "requirements": "US citizen 18-24, bachelor's degree, exceptional leadership and academics",
        "location": "Oxford, UK",
    },
    {
        "title": "National Merit Scholarship",
        "organization": "National Merit Scholarship Corporation",
        "amount": "$2,500 (corporate/college awards vary)",
        "deadline": "Based on PSAT scores (junior year)",
        "url": "https://www.nationalmerit.org",
        "description": "Based on PSAT/NMSQT scores. Gateway to many corporate and college-specific awards.",
        "requirements": "US high school junior, PSAT score in top ~1%",
        "location": "United States",
    },
    {
        "title": "Regeneron Science Talent Search",
        "organization": "Regeneron / Society for Science",
        "amount": "Up to $250,000",
        "deadline": "November",
        "url": "https://www.societyforscience.org/regeneron-sts/",
        "description": "Most prestigious science and math competition for high school seniors.",
        "requirements": "High school senior with original research project in STEM",
        "location": "United States",
    },
    {
        "title": "Google Generation Scholarship",
        "organization": "Google",
        "amount": "$10,000",
        "deadline": "December",
        "url": "https://buildyourfuture.withgoogle.com/scholarships",
        "description": "For students from underrepresented groups studying Computer Science or related field.",
        "requirements": "Enrolled in CS or related degree, strong academic record, demonstrated leadership",
        "location": "United States/Canada",
    },
    {
        "title": "Dell Scholars Program",
        "organization": "Michael & Susan Dell Foundation",
        "amount": "$20,000 + laptop + resources",
        "deadline": "December 1",
        "url": "https://www.dellscholars.org",
        "description": "For college-bound students who have demonstrated need and effort to succeed.",
        "requirements": "Participant in college readiness program, financial need, GPA 2.4+",
        "location": "United States",
    },
    {
        "title": "Burger King Scholars Program",
        "organization": "Burger King McLamore Foundation",
        "amount": "$1,000 – $50,000",
        "deadline": "December 15",
        "url": "https://www.bkmclamorefoundation.org",
        "description": "For BK employees, their children, and high school seniors.",
        "requirements": "High school senior or BK employee, GPA 2.5+, financial need",
        "location": "United States",
    },
    {
        "title": "Horatio Alger Scholarship",
        "organization": "Horatio Alger Association",
        "amount": "$25,000",
        "deadline": "October 25",
        "url": "https://scholars.horatioalger.org",
        "description": "For students who have overcome adversity and demonstrated integrity and perseverance.",
        "requirements": "High school senior, financial need (under $55k household income), GPA 2.0+, US citizen",
        "location": "United States",
    },
    {
        "title": "AXA Achievement Scholarship",
        "organization": "AXA Foundation",
        "amount": "$10,000 – $25,000",
        "deadline": "December 15",
        "url": "https://us.axa.com/axa-foundation/scholarship.html",
        "description": "For students who have demonstrated outstanding achievement in school or community.",
        "requirements": "High school senior, US citizen/permanent resident, GPA 3.0+",
        "location": "United States",
    },
    {
        "title": "Hispanic Scholarship Fund",
        "organization": "Hispanic Scholarship Fund",
        "amount": "$500 – $5,000",
        "deadline": "February 15",
        "url": "https://www.hsf.net",
        "description": "Largest scholarship provider for Hispanic American students in the US.",
        "requirements": "Hispanic heritage, US citizen/permanent resident, GPA 3.0+, enrolled in college",
        "location": "United States",
    },
    {
        "title": "Thurgood Marshall College Fund",
        "organization": "Thurgood Marshall College Fund",
        "amount": "Varies ($4,000+)",
        "deadline": "March",
        "url": "https://www.tmcf.org",
        "description": "For students attending Historically Black Colleges and Universities (HBCUs).",
        "requirements": "Enrolled at HBCU, US citizen, GPA 3.0+, financial need",
        "location": "United States",
    },
    {
        "title": "AmeriCorps Education Award",
        "organization": "AmeriCorps",
        "amount": "$7,395 (full-time term)",
        "deadline": "Rolling",
        "url": "https://americorps.gov",
        "description": "Education award for completing a term of service with AmeriCorps.",
        "requirements": "Complete AmeriCorps service term, US citizen, 17+",
        "location": "United States",
    },
    {
        "title": "Udall Scholarship",
        "organization": "Morris K. Udall Foundation",
        "amount": "$7,000",
        "deadline": "March (varies by institution)",
        "url": "https://udall.gov",
        "description": "For college sophomores and juniors committed to careers related to environment or Native American issues.",
        "requirements": "College sophomore or junior, US citizen, environmental/tribal policy focus",
        "location": "United States",
    },
    {
        "title": "Truman Scholarship",
        "organization": "Harry S. Truman Scholarship Foundation",
        "amount": "$30,000",
        "deadline": "February (varies by institution)",
        "url": "https://www.truman.gov",
        "description": "For college juniors committed to careers in public service.",
        "requirements": "College junior, US citizen, public service commitment, GPA 3.0+",
        "location": "United States",
    },
    {
        "title": "Gilman International Scholarship",
        "organization": "U.S. Department of State",
        "amount": "Up to $5,000",
        "deadline": "March / October (two cycles)",
        "url": "https://www.gilmanscholarship.org",
        "description": "For Pell Grant recipients who wish to study or intern abroad.",
        "requirements": "Pell Grant recipient, US citizen, enrolled in accredited US college",
        "location": "International study abroad",
    },
    {
        "title": "Point Foundation Scholarship",
        "organization": "Point Foundation",
        "amount": "Varies (up to full cost)",
        "deadline": "January",
        "url": "https://pointfoundation.org",
        "description": "For LGBTQ+ students demonstrating leadership and academic excellence.",
        "requirements": "LGBTQ+ identifying, enrolled in college, strong academics, financial need",
        "location": "United States",
    },
    {
        "title": "Davis-Putter Scholarship",
        "organization": "Davis-Putter Scholarship Fund",
        "amount": "Up to $15,000",
        "deadline": "April 1",
        "url": "https://davisputter.org",
        "description": "For activists working for social and economic justice who are enrolled in college.",
        "requirements": "Enrolled in college, financial need, activism/social justice involvement",
        "location": "United States",
    },
    {
        "title": "UNCF Scholarships",
        "organization": "United Negro College Fund",
        "amount": "Varies ($2,000–$20,000+)",
        "deadline": "Rolling (multiple programs)",
        "url": "https://uncf.org",
        "description": "Hundreds of scholarship programs for Black/African American college students.",
        "requirements": "African American student, enrolled in college, financial need, GPA 2.5+",
        "location": "United States",
    },
    {
        "title": "Astronaut Scholarship",
        "organization": "Astronaut Scholarship Foundation",
        "amount": "$15,000",
        "deadline": "April (nominated by institution)",
        "url": "https://astronautscholarship.org",
        "description": "For exceptional college juniors and seniors in STEM pursuing research careers.",
        "requirements": "US citizen, junior or senior in STEM, strong research focus, nominated by institution",
        "location": "United States",
    },
    {
        "title": "Elks Most Valuable Student Scholarship",
        "organization": "Elks National Foundation",
        "amount": "$1,000 – $12,500",
        "deadline": "November 12",
        "url": "https://www.elks.org/scholars/scholarships/mvs.cfm",
        "description": "Merit-based scholarship for high school seniors, one of the largest in the US.",
        "requirements": "High school senior, US citizen, leadership qualities",
        "location": "United States",
    },
    {
        "title": "Scholarships.com Annual Scholarship",
        "organization": "Scholarships.com",
        "amount": "$10,000",
        "deadline": "December 31",
        "url": "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-type/scholarships-com-annual-scholarship/",
        "description": "Open to all college students based on essay submission.",
        "requirements": "Enrolled or enrolling in college, US citizen",
        "location": "United States",
    },
    {
        "title": "Chegg Annual Scholarship",
        "organization": "Chegg",
        "amount": "$1,000",
        "deadline": "Rolling",
        "url": "https://www.chegg.com",
        "description": "Multiple scholarships offered through Chegg for current college students.",
        "requirements": "Enrolled in college, varies by program",
        "location": "United States",
    },
]
